console.log("Process 1")
console.log("Process 2")
console.log("Process 3")
setTimeout(() =>(console.log("Process 8")),12000)
console.log("Process 4")
console.log("Process 5")
console.log("Process 6")
setTimeout(() =>(console.log("Process 7")),500)
console.log("Process 9")